apiVersion: v2
name: webapp
description: A Helm chart for deploying a web application on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - web
  - application
  - kubernetes

maintainers:
  - name: DevOps Team
    email: devops@example.com

home: https://github.com/example/webapp
sources:
  - https://github.com/example/webapp

icon: https://example.com/icon.png
