apiVersion: v2
name: logging-stack
description: ELK stack for centralized logging
type: application
version: 1.0.0

dependencies:
  - name: elasticsearch
    version: "19.x.x"
    repository: "https://helm.elastic.co"
  - name: kibana
    version: "10.x.x"
    repository: "https://helm.elastic.co"
  - name: filebeat
    version: "8.x.x"
    repository: "https://helm.elastic.co"
